[project]
name = "py-pt-tf-stock-fluctuations-classification"
version = "0.1.0"
description = "Stocks go up and down based on market sentiment."
authors = [{ name = "Shawn Yu" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
